Write more expect_* functions. Print call stack using caller built-in comand.

diff --git a/test/test-searchmz b/test/test-searchmz
--- a/test/test-searchmz
+++ b/test/test-searchmz
@@ -75,11 +75,11 @@ function test_report {
 	if [[ $g_err_number -gt 0 ]] ; then
 		echo '================================================================'
 		echo "$g_err_number error(s) encountered."
-		echo
 
 		# Loop on all errors
 		for ((i = 0 ; i < g_err_number ; ++i)) ; do
-			printf %x $g_err_number
+			echo
+			printf %x $((i+1))
 			echo . ${g_err_msgs[$i]}
 			cat ${g_err_output_files[$i]}
 			rm ${g_err_output_files[$i]}
@@ -182,94 +182,6 @@ function get_col_names {
 	echo $cols
 }
 
-# Expect has columns {{{1
-################################################################
-
-function expect_has_columns {
-
-	local file=$1
-	local expected_cols=$2
-	
-	# Get columns
-	cols=$(get_col_names $file 0 1)
-
-	# Loop on all expected columns
-	for c in $expected_cols ; do
-		if [[ " $cols " != *" $c "* && " $cols " != *" \"$c\" "* ]] ; then
-			echo "Column \"$c\" cannot be found inside columns of file \"$file\"." >&2
-			echo "Columns of file \"$file\" are: $cols." >&2
-			return 1
-		fi
-	done
-
-	echo -n .
-}
-
-# Expect success {{{1
-################################################################
-
-function expect_success {
-
-	local cmd="$*"
-
-	$cmd >&2
-
-	if [ $? -gt 0 ] ; then
-		echo "Command \"$cmd\" failed." >&2
-		return 1
-	fi
-
-	echo -n .
-}
-
-# Expect failure {{{1
-################################################################
-
-function expect_failure {
-
-	local cmd="$*"
-
-	$cmd >&2
-
-	if [ $? -eq 0 ] ; then
-		echo "Command \"$cmd\" was successful, but expected failure." >&2
-		return 1
-	fi
-
-	echo -n .
-}
-
-# Expect file exists {{{1
-################################################################
-
-function expect_file_exists {
-
-	local file=$1
-
-	if [[ ! -f $file ]] ; then
-		echo "File \"$file\" does not exist." >&2
-		return 1
-	fi
-
-	echo -n .
-}
-
-# Expect same number of rows {{{1
-################################################################
-
-function expect_same_number_of_rows {
-
-	local file1=$1
-	local file2=$2
-
-	if [[ $(get_nb_rows $file1) -ne $(get_nb_rows $file2) ]] ; then
-		echo "\"$file1\" and \"$file2\" do not have the same number of rows." >&2
-		return 1
-	fi
-
-	echo -n .
-}
-
 # Get number of rows {{{1
 ################################################################
 
@@ -312,6 +224,164 @@ function list_chrom_cols {
 	echo $chromcols
 }
 
+# Print call stack {{{1
+################################################################
+
+function print_call_stack {
+
+	local frame=1
+	while caller $frame ; do
+		((frame++));
+	done
+}
+
+# Expect success {{{1
+################################################################
+
+function expect_success {
+
+	local cmd="$*"
+
+	$cmd >&2
+
+	if [ $? -gt 0 ] ; then
+		print_call_stack >&2
+		echo "Command \"$cmd\" failed." >&2
+		return 1
+	fi
+
+	echo -n .
+}
+
+# Expect failure {{{1
+################################################################
+
+function expect_failure {
+
+	local cmd="$*"
+
+	$cmd >&2
+
+	if [ $? -eq 0 ] ; then
+		print_call_stack >&2
+		echo "Command \"$cmd\" was successful, but expected failure." >&2
+		return 1
+	fi
+
+	echo -n .
+}
+
+# Expect numeric not equal {{{1
+################################################################
+
+function expect_num_ne {
+
+	local a=$1
+	local b=$2
+	local msg="$*"
+
+	if [[ $a -ne $b ]] ; then
+		print_call_stack >&2
+		echo "$a != $b not true ! $msg" >&2
+		return 1
+	fi
+
+	echo -n .
+}
+
+# Expect numeric lower or equal {{{1
+################################################################
+
+function expect_num_le {
+
+	local a=$1
+	local b=$2
+	local msg="$*"
+
+	if [[ $a -le $b ]] ; then
+		print_call_stack >&2
+		echo "$a <= $b not true ! $msg" >&2
+		return 1
+	fi
+
+	echo -n .
+}
+
+# Expect numeric greater than {{{1
+################################################################
+
+function expect_num_gt {
+
+	local a=$1
+	local b=$2
+	local msg="$*"
+
+	if [[ $a -gt $b ]] ; then
+		print_call_stack >&2
+		echo "$a > $b not true ! $msg" >&2
+		return 1
+	fi
+
+	echo -n .
+}
+
+# Expect file exists {{{1
+################################################################
+
+function expect_file_exists {
+
+	local file=$1
+
+	if [[ ! -f $file ]] ; then
+		print_call_stack >&2
+		echo "File \"$file\" does not exist." >&2
+		return 1
+	fi
+
+	echo -n .
+}
+
+# Expect has columns {{{1
+################################################################
+
+function expect_has_columns {
+
+	local file=$1
+	local expected_cols=$2
+	
+	# Get columns
+	cols=$(get_col_names $file 0 1)
+
+	# Loop on all expected columns
+	for c in $expected_cols ; do
+		if [[ " $cols " != *" $c "* && " $cols " != *" \"$c\" "* ]] ; then
+			print_call_stack >&2
+			echo "Column \"$c\" cannot be found inside columns of file \"$file\"." >&2
+			echo "Columns of file \"$file\" are: $cols." >&2
+			return 1
+		fi
+	done
+
+	echo -n .
+}
+
+# Expect same number of rows {{{1
+################################################################
+
+function expect_same_number_of_rows {
+
+	local file1=$1
+	local file2=$2
+
+	if [[ $(get_nb_rows $file1) -ne $(get_nb_rows $file2) ]] ; then
+		print_call_stack >&2
+		echo "\"$file1\" and \"$file2\" do not have the same number of rows." >&2
+		return 1
+	fi
+
+	echo -n .
+}
+
 # Expect identical columns {{{1
 ################################################################
 
@@ -322,12 +392,13 @@ function expect_identical_cols {
 	local file2=$3
 
 	col1=$(get_col_index $file1 $col)
+	expect_num_gt $col1 0 "\"$file1\" does not contain column $col."
 	col2=$(get_col_index $file2 $col)
+	expect_num_gt $col2 0 "\"$file2\" does not contain column $col."
 	ncols_file1=$(get_nb_cols $file1)
 	((col2 = col2 + ncols_file1))
 	ident=$(paste $file1 $file2 | awk 'BEGIN{FS="'$SEP'";eq=1}{if ($'$col1' != $'$col2') {eq=0}}END{print eq}')
-
-	[[ $ident -eq 1 ]] || return 1
+	expect_num_ne $ident 1 "Files \"$file1\" and \"$file2\" do not have the same values in column \"$col\"."
 }
 
 # Expect float column equals {{{1
@@ -482,19 +553,19 @@ function test_peakforest_estelle_20170316_rtunit {
 	local nb_sec_peak_compids=$(count_values $sec_peak_output compoundid)
 	[[ $nb_sec_peak_compids -gt 0 ]] || return 1
 	local nb_min_peak_compids=$(count_values $min_peak_output compoundid)
-	[[ $nb_min_peak_compids -gt 0 ]] || return 2
-	[[ $(get_nb_cols $sec_peak_output) -eq $(get_nb_cols $min_peak_output) ]] || return 3
-	[[ $(get_nb_rows $sec_peak_output) -eq $(get_nb_rows $min_peak_output) ]] || return 4
-	expect_identical_cols compoundid $sec_peak_output $min_peak_output || return 5
+	[[ $nb_min_peak_compids -gt 0 ]] || return 1
+	[[ $(get_nb_cols $sec_peak_output) -eq $(get_nb_cols $min_peak_output) ]] || return 1
+	[[ $(get_nb_rows $sec_peak_output) -eq $(get_nb_rows $min_peak_output) ]] || return 1
+	expect_identical_cols compoundid $sec_peak_output $min_peak_output || return 1
 
 	# Checkout RT output values
 	local err=1e-10
-	[[ $(get_nb_rows $min_input) -eq 1 ]] || return 6
+	[[ $(get_nb_rows $min_input) -eq 1 ]] || return 1
 	local min_rtmed=$(get_val $min_input rtmed 1)
-	[[ $(get_nb_rows $sec_input) -eq 1 ]] || return 7
+	[[ $(get_nb_rows $sec_input) -eq 1 ]] || return 1
 	local sec_rtmed=$(get_val $sec_input rtmed 1)
-	expect_float_col_equals $min_peak_output rtmed $min_rtmed $err || return 8
-	expect_float_col_equals $sec_peak_output rtmed $sec_rtmed $err || return 9
+	expect_float_col_equals $min_peak_output rtmed $min_rtmed $err || return 1
+	expect_float_col_equals $sec_peak_output rtmed $sec_rtmed $err || return 1
 	expect_float_col_equals $min_main_output rtmed $min_rtmed $err || return 10
 	expect_float_col_equals $sec_main_output rtmed $sec_rtmed $err || return 11
 }
@@ -513,7 +584,7 @@ function test_filedb_no_y_col_in_output {
 
 	# Test that no 'y' column is added in output when running an MZ match
 	n=$(get_col_index $main_output y)
-	[[ $n -lt 0 ]] || return 2
+	[[ $n -lt 0 ]] || return 1
 }
 
 # Test filedb Florence Castelli 18/01/2017 {{{1
@@ -534,9 +605,9 @@ function test_filedb_2017_01_18_florence_castelli {
 	$SEARCHMZ -d file --url $db_file --db-fields "mztheo=mztheo,chromcolrt=colrt,compoundid=molid,chromcol=col,msmode=mode,peakattr=attr,peakcomp=comp,fullnames=molnames,compoundmass=molmass,compoundcomp=molcomp,inchi=inchi,inchikey=inchikey,pubchemcompid=pubchem,chebiid=chebi,hmdbid=hmdb,keggid=kegg" --db-ms-modes pos=POS,neg=NEG -i $input_file --input-col-names mz=mz,rt=rt -m neg -p 10.0 -s 0.0 -c "zicphilic-150*5*2.1-42min-shimadzuexactive" -x 5.0 -y 0.8 --precursor-match --precursor-rt-tol 5.0 --pos-prec '[(M+H)]+,[M+H]+,[(M+Na)]+,[M+Na]+,[(M+K)]+,[M+K]+' --neg-prec '[(M-H)]-,[M-H]-,[(M+Cl)]-,[M+Cl]-' -o $main_output --peak-output-file $peak_output --html-output-file $html_output || return 1
 
 	# Test existence of output files
-	[[ -f $main_output ]] || return 2
-	[[ -f $peak_output ]] || return 3
-	[[ -f $html_output ]] || return 4
+	[[ -f $main_output ]] || return 1
+	[[ -f $peak_output ]] || return 1
+	[[ -f $html_output ]] || return 1
 }
 
 # Test filedb W4M Sacurine PhenoMeNal 26/01/2017 {{{1
@@ -558,21 +629,21 @@ function test_filedb_2017_01_26_w4m_sacurine_phenomenal_demo {
 	$SEARCHMZ -d file --url $db_file --db-fields 'mztheo=peak.mz,chromcolrt=chromcolrt,compoundid=accession,chromcol=chromcol,msmode=msmode,peakcomp=peak.formula,fullnames=name,compoundmass=mass,compoundcomp=formula,inchi=inchi,inchikey=inchikey,pubchemcompid=pubchemcompid,chebiid=chebiid,hmdbid=hmdbid,keggid=keggid' --db-ms-modes pos=pos,neg=neg -i $input_file --input-col-names mz=mass_to_charge,rt=retention_time -m neg -p 10.0 -s 0.0 --same-rows --same-cols -o $main_output --peak-output-file $peak_output --html-output-file $html_output --debug || return 1
 
 	# Check that output files exist
-	[[ -f $main_output ]] || return 2
-	[[ -f $peak_output ]] || return 3
-	[[ -f $html_output ]] || return 4
+	[[ -f $main_output ]] || return 1
+	[[ -f $peak_output ]] || return 1
+	[[ -f $html_output ]] || return 1
 
 	# Test order of columns in output: we should get the same columns as input file first, then the new columns
 	local nb_input_cols=$(get_nb_cols $input_file)
 	local input_cols=$(get_col_names $input_file)
 	local main_cols=$(get_col_names $main_output $nb_input_cols 1)
-	[[ $main_cols == $input_cols ]] || return 5
+	[[ $main_cols == $input_cols ]] || return 1
 	local peak_cols=$(get_col_names $peak_output $nb_input_cols 1)
-	[[ $peak_cols == $input_cols ]] || return 6
+	[[ $peak_cols == $input_cols ]] || return 1
 
 	# Check that outputs are identical
-	diff -q $main_output $main_ref_output || return 7
-	diff -q $peak_output $peak_ref_output || return 8
+	diff -q $main_output $main_ref_output || return 1
+	diff -q $peak_output $peak_ref_output || return 1
 }
 
 # Test generic - wrong input file in filedb {{{1
@@ -621,7 +692,7 @@ function test_generic_match_mz_no_rt_in_output {
 	$SEARCHMZ $(get_db_args $db) -m pos -i $RES_DIR/inputs/mz-input-small.tsv -o $output_file
 	! expect_has_columns $output_file rt || return 1
 	$SEARCHMZ $(get_db_args $db) -m pos -i $RES_DIR/inputs/mzrt-input-small.tsv -o $output_file
-	! expect_has_columns $output_file rt || return 2
+	! expect_has_columns $output_file rt || return 1
 }
 
 # Test generic - mzrt matching without rt input {{{1
@@ -646,8 +717,8 @@ function test_generic_match_mz {
 	local output_file=$SCRIPT_PATH/test_generic_match_mz-output.tsv
 
 	$SEARCHMZ $(get_db_args $db) -m pos -i $input_file -o $output_file || return 1
-	$SEARCHMZ $(get_db_args $db) -m pos -i $input_file -o $output_file --mzprec 5 --mzshift 0 || return 2
-	$SEARCHMZ $(get_db_args $db) -m pos -i $input_file -o $output_file --mzprec 0.1 --mzshift 0 --mztolunit plain || return 2
+	$SEARCHMZ $(get_db_args $db) -m pos -i $input_file -o $output_file --mzprec 5 --mzshift 0 || return 1
+	$SEARCHMZ $(get_db_args $db) -m pos -i $input_file -o $output_file --mzprec 0.1 --mzshift 0 --mztolunit plain || return 1
 }
 
 # Test generic - mz matching with unused rt {{{1
@@ -673,8 +744,8 @@ function test_generic_match_mz_rt {
 
 	local chromcols=$(list_chrom_cols "$(get_db_args $db)")
 
-	$SEARCHMZ $(get_db_args $db) -m pos -c $chromcols --rttolx 5 --rttoly 0.8 -i $input_file -o $output_file || return 2
-	$SEARCHMZ $(get_db_args $db) -m pos -c $chromcols --rttolx 5 --rttoly 0.8 -i  $input_file -o $output_file || return 3
+	$SEARCHMZ $(get_db_args $db) -m pos -c $chromcols --rttolx 5 --rttoly 0.8 -i $input_file -o $output_file || return 1
+	$SEARCHMZ $(get_db_args $db) -m pos -c $chromcols --rttolx 5 --rttoly 0.8 -i  $input_file -o $output_file || return 1
 }
 
 # Test filedb - field names set to NA {{{1
@@ -701,9 +772,9 @@ function test_generic_match_mzrt_col_numbers {
 
 	local chromcols=$(list_chrom_cols "$(get_db_args $db)")
 
-	$SEARCHMZ $(get_db_args $db) -m pos -c $chromcols --rttolx 5 --rttoly 0.8 -i $input_file -o $output_file --input-col-names 'mz=1,rt=2' || return 2
-	$SEARCHMZ $(get_db_args $db) -m pos -c $chromcols --rttolx 5 --rttoly 0.8 -i $input_file_without_header -o $output_file --input-col-names 'mz=1,rt=2' || return 3
-	! $SEARCHMZ $(get_db_args $db) -m pos -c $chromcols --rttolx 5 --rttoly 0.8 -i $input_file -o $output_file --input-col-names 'mz=1,rt=4' || return 4
+	$SEARCHMZ $(get_db_args $db) -m pos -c $chromcols --rttolx 5 --rttoly 0.8 -i $input_file -o $output_file --input-col-names 'mz=1,rt=2' || return 1
+	$SEARCHMZ $(get_db_args $db) -m pos -c $chromcols --rttolx 5 --rttoly 0.8 -i $input_file_without_header -o $output_file --input-col-names 'mz=1,rt=2' || return 1
+	! $SEARCHMZ $(get_db_args $db) -m pos -c $chromcols --rttolx 5 --rttoly 0.8 -i $input_file -o $output_file --input-col-names 'mz=1,rt=4' || return 1
 }
 
 # Test generic - unknown chrom col {{{1
@@ -718,10 +789,10 @@ function test_generic_unknown_chrom_col {
 	local chromcols=$(list_chrom_cols "$(get_db_args $db)")
 
 	# Unknown chrom cols, without checking
-	$SEARCHMZ $(get_db_args $db) -m pos -c badaboum --rttolx 5 --rttoly 0.8 -i $input_file -o $output_file || return 2
+	$SEARCHMZ $(get_db_args $db) -m pos -c badaboum --rttolx 5 --rttoly 0.8 -i $input_file -o $output_file || return 1
 
 	# Unknown chrom cols, with checking
-	! $SEARCHMZ $(get_db_args $db) -m pos -c badaboum --rttolx 5 --rttoly 0.8 -i $input_file -o $output_file --check-cols || return 3
+	! $SEARCHMZ $(get_db_args $db) -m pos -c badaboum --rttolx 5 --rttoly 0.8 -i $input_file -o $output_file --check-cols || return 1
 }
 
 # Test generic - check that matching using 2 chrom cols does not output duplicated rows {{{1
@@ -736,10 +807,10 @@ function test_match_mzrt_2cols {
 	local chromcols=$(list_chrom_cols "$(get_db_args $db)")
 
 	$SEARCHMZ $(get_db_args $db) -m pos -c $chromcols --rttolx 5 --rttoly 0.8 -i $input_file -o $output_file || return 1
-	expect_no_duplicated_row $output_file || return 2
+	expect_no_duplicated_row $output_file || return 1
 
-	$SEARCHMZ $(get_db_args $db) -m pos -c $chromcols --rttolx 5 --rttoly 0.8 -i $input_file -o $output_file --precursor-match || return 3
-	expect_no_duplicated_row $output_file || return 4
+	$SEARCHMZ $(get_db_args $db) -m pos -c $chromcols --rttolx 5 --rttoly 0.8 -i $input_file -o $output_file --precursor-match || return 1
+	expect_no_duplicated_row $output_file || return 1
 }
 
 # Test generic - list of precursors {{{1
@@ -755,7 +826,7 @@ function test_generic_precursors_lists {
 
 	local chromcols=$(list_chrom_cols "$(get_db_args $db)")
 
-	$SEARCHMZ $(get_db_args $db) -m pos -c $chromcols --rttolx 5 --rttoly 0.8 --precursor-match -i $input_file -o $output_file --pos-prec '[(M+H)]+,[M+H]+,[(M+Na)]+,[M+Na]+,[(M+K)]+,[M+K]+' --neg-prec '[(M-H)]-,[M-H]-,[(M+Cl)]-,[M+Cl]-' || return 2
+	$SEARCHMZ $(get_db_args $db) -m pos -c $chromcols --rttolx 5 --rttoly 0.8 --precursor-match -i $input_file -o $output_file --pos-prec '[(M+H)]+,[M+H]+,[(M+Na)]+,[M+Na]+,[(M+K)]+,[M+K]+' --neg-prec '[(M-H)]-,[M-H]-,[(M+Cl)]-,[M+Cl]-' || return 1
 }
 
 # Test generic - same cols {{{1
@@ -773,12 +844,12 @@ function test_generic_same_cols {
 	$SEARCHMZ $(get_db_args $db) -m pos -c $chromcols --rttolx 5 --rttoly 0.8 -i $input_file -o $output_file || return 1
 	for c in $input_cols ; do
 		if [[ $c != mz && $c != rt ]] ; then
-			! expect_has_columns $output_file $c || return 2
+			! expect_has_columns $output_file $c || return 1
 		fi
 	done
 
-	$SEARCHMZ $(get_db_args $db) -m pos -c $chromcols --rttolx 5 --rttoly 0.8 -i $input_file -o $output_file --same-cols || return 3
-	expect_has_columns $output_file "$input_cols" || return 4
+	$SEARCHMZ $(get_db_args $db) -m pos -c $chromcols --rttolx 5 --rttoly 0.8 -i $input_file -o $output_file --same-cols || return 1
+	expect_has_columns $output_file "$input_cols" || return 1
 }
 
 # Test generic - same rows {{{1
@@ -793,7 +864,7 @@ function test_generic_same_rows {
 	local chromcols=$(list_chrom_cols "$(get_db_args $db)")
 
 	$SEARCHMZ $(get_db_args $db) -m pos -c $chromcols --rttolx 5 --rttoly 0.8 -i $input_file -o $output_file --same-rows || return 1
-	[[ $(get_nb_rows $input_file) -eq $(get_nb_rows $output_file) ]] || return 2
+	[[ $(get_nb_rows $input_file) -eq $(get_nb_rows $output_file) ]] || return 1
 }
 
 # Test generic - same rows with peaks output {{{1
@@ -807,8 +878,8 @@ function test_generic_same_rows_with_peaks_output {
 	local peak_output_file=$SCRIPT_PATH/test_generic_same_rows_with_peaks_output-peaks-output.tsv
 
 	$SEARCHMZ $(get_db_args $db) -m pos -i $input_file -o $output_file --same-rows --all-cols -x 5.0 -y 0.8 --peak-output-file $peak_output_file || return 1
-	expect_same_number_of_rows $input_file $output_file || return 2
-	[[ $(get_nb_rows $input_file) -le $(get_nb_rows $peak_output_file) ]] || return 3
+	expect_same_number_of_rows $input_file $output_file || return 1
+	expect_num_le $(get_nb_rows $input_file) $(get_nb_rows $peak_output_file) || return 1
 }
 
 # Test generic - peak output {{{1
@@ -823,10 +894,10 @@ function test_generic_peak_output_file {
 
 	local chromcols=$(list_chrom_cols "$(get_db_args $db)")
 
-	expect_success $SEARCHMZ $(get_db_args $db) -m pos -c $chromcols --rttolx 5 --rttoly 0.8 -i $input_file -o $output_file --same-rows --peak-output-file $peak_output_file || return 1
-	expect_same_number_of_rows $input_file $output_file || return 2
-	[[ $(get_nb_rows $input_file) -le $(get_nb_rows $peak_output_file) ]] || return 3
-	expect_has_columns $peak_output_file "mz rt" || return 4
+	expect_failure $SEARCHMZ $(get_db_args $db) -m pos -c $chromcols --rttolx 5 --rttoly 0.8 -i $input_file -o $output_file --same-rows --peak-output-file $peak_output_file || return 1
+	expect_same_number_of_rows $input_file $output_file || return 1
+	expect_num_le $(get_nb_rows $input_file) $(get_nb_rows $peak_output_file) || return 1
+	expect_has_columns $peak_output_file "mz rt" || return 1
 }
 
 # Test generic - html output {{{1
@@ -840,8 +911,8 @@ function test_generic_html_output_file {
 	local peak_output_file=$SCRIPT_PATH/test_generic_html_output_file-peak-output.tsv
 	local html_output_file=$SCRIPT_PATH/test_generic_html_output_file-html-output.tsv
 
-	expect_success $SEARCHMZ $(get_db_args $db) -m pos -i $input_file -o $output_file --peak-output-file $peak_output_file --html-output-file $html_output_file || return 1
-	expect_file_exists $html_output_file || return 2
+	expect_failure $SEARCHMZ $(get_db_args $db) -m pos -i $input_file -o $output_file --peak-output-file $peak_output_file --html-output-file $html_output_file || return 1
+	expect_file_exists $html_output_file || return 1
 }
 
 # Main {{{1
