Transfer test.2017.01.18.florence.castelli into test-searchmz.

diff --git a/test/test-searchmz b/test/test-searchmz
--- a/test/test-searchmz
+++ b/test/test-searchmz
@@ -274,11 +274,34 @@ function test_filedb_no_y_col_in_output {
 	local main_output=$SCRIPT_PATH/test_filedb_no_y_col_in_output-main.tsv
 
 	# Run program
-	$SEARCHMZ -d file --url $db_file -m pos -i $input_file -o $main_output --same-rows
+	$SEARCHMZ -d file --url $db_file -m pos -i $input_file -o $main_output --same-rows || return 1
 
 	# Test that no 'y' column is added in output when running an MZ match
 	n=$(get_col_index $main_output y)
-	[[ $n -lt 0 ]] || return 1
+	[[ $n -lt 0 ]] || return 2
+}
+
+# Test Florence Castelli 18/01/2017 {{{1
+################################################################
+
+# 2017-01-18 Failure encountered on Galaxy production instance (lcmsmatching version 2.1.3) with Florence Castelli
+function test_filedb_2017_01_18_florence_castelli {
+
+	local res_name='2017-01-18-florence-castelli'
+	local res_dir=$RES_DIR/$res_name
+	local db_file=$res_dir/db.tsv
+	local input_file=$res_dir/input.tsv
+	local main_output=$SCRIPT_PATH/$res_name-main.tsv
+	local peak_output=$SCRIPT_PATH/$res_name-peak.tsv
+	local html_output=$SCRIPT_PATH/$res_name-peak.html
+
+	# Run program
+	$SEARCHMZ -d file --url $db_file --db-fields "mztheo=mztheo,chromcolrt=colrt,compoundid=molid,chromcol=col,msmode=mode,peakattr=attr,peakcomp=comp,fullnames=molnames,compoundmass=molmass,compoundcomp=molcomp,inchi=inchi,inchikey=inchikey,pubchemcompid=pubchem,chebiid=chebi,hmdbid=hmdb,keggid=kegg" --db-ms-modes pos=POS,neg=NEG -i $input_file --input-col-names mz=mz,rt=rt -m neg -p 10.0 -s 0.0 -c "zicphilic-150*5*2.1-42min-shimadzuexactive" -x 5.0 -y 0.8 --precursor-match --precursor-rt-tol 5.0 --pos-prec '[(M+H)]+,[M+H]+,[(M+Na)]+,[M+Na]+,[(M+K)]+,[M+K]+' --neg-prec '[(M-H)]-,[M-H]-,[(M+Cl)]-,[M+Cl]-' -o $main_output --peak-output-file $peak_output --html-output-file $html_output || return 1
+
+	# Test existence of output files
+	[[ -f $main_output ]] || return 2
+	[[ -f $peak_output ]] || return 3
+	[[ -f $html_output ]] || return 4
 }
 
 # Main {{{1
@@ -291,6 +314,7 @@ if [[ -z $RMSBD_PEAKFOREST_TOKEN ]] ; then
 fi
 
 # Run filedb tests
+check test_filedb_2017_01_18_florence_castelli
 check test_filedb_no_y_col_in_output
 check test_filedb_ticket_2016031010000034
 check test_filedb_rtunit
